# baseURL: https://kicka42.github.io
baseURL: https://kicka.org
languageCode: en-us
title: Kicka
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Hi, I'm Kicka.
    Content: A Python coder, data scientist and AI developer, sculpting innovative projects. My long-term goal is to grow professionally and take on new challenges all the time. I value continuous learning and working with highly motivated people. Besides, I'm keen on reading books, playing guitar, meeting new people & travelling around the world.


  homeImage: "content/assets/egon-schiele_self-portrait-with-raised-arms_1914.jpg"
  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/kicka/"
    - name: "github"
      url: "https://github.com/kicka42"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #  url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: false
  author: "Kicka"
  contact: "kicka@example.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    #- identifier: categories
    #  name: Categories
    #  url: /categories/
    #  weight: 10
    # - identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 40
    #- identifier: search
    #  name: Search
    #  url: /search/
    #  weight: 20
    #- identifier: archive
    #  name: Archive
    #  url: /archives/
    #  weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
