name: github pages

on:
  push:
    branches:
      - main # Triggers the workflow on push events to the main branch
  pull_request:
    branches:
      - main # Ensures the workflow is also triggered on pull requests to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Copy CNAME
        run: cp CNAME ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true # Keeps files that are already in the gh-pages branch
